name = "pwr-checkout-web-pixel"
type = "web_pixel_extension"
runtime_context = "strict"

[settings]
type = "object"

[settings.fields.merchantGroupId]
name = "Merchant Group ID"
type = "single_line_text_field"

[settings.fields.merchantId]
name = "Merchant ID"
type = "single_line_text_field"

[settings.fields.locale]
name = "Locale"
type = "single_line_text_field"
